In [29]:
import nashpy as nash
import numpy as np
from sklearn.preprocessing import MinMaxScaler

H = np.array([[0.38, 0.73, 1.01], 
              [0.31, 0.64, 0.92], 
              [0.41, 0.75, 1.04]]) # Haryana data

MP = np.array([[0.47, 0.54, 0.57], 
               [0.39, 0.45, 0.49], 
               [0.50, 0.57, 0.61]]) # MP data

game = nash.Game(H,MP) # Create 2 player game

print("Game representation:")
print(game)

equilibria = game.support_enumeration() # Find equilibrium

print("\nNash Equilibria:")
for eq in equilibria:
    print(eq)

Game representation:
Bi matrix game with payoff matrices:

Row player:
[[0.38 0.73 1.01]
 [0.31 0.64 0.92]
 [0.41 0.75 1.04]]

Column player:
[[0.47 0.54 0.57]
 [0.39 0.45 0.49]
 [0.5  0.57 0.61]]

Nash Equilibria:
(array([0., 0., 1.]), array([0., 0., 1.]))


In [11]:
!pip install nashpy


[notice] A new release of pip is available: 23.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip
